### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: Omarchy Bootloader
interface_branding_color: aaaaaa
interface_help_color: 888888
interface_help_color_bright: aaaaaa
hash_mismatch_panic: no

term_background: 000000
backdrop: 000000

# Terminal colors (43pr monochrome silver)
term_palette: 000000;e8e8e8;d0d0d0;b0b0b0;a0a0a0;d8d8d8;bcbcbc;aaaaaa
term_palette_bright: 5d5d5d;ffffff;e8e8e8;d0d0d0;c0c0c0;f0f0f0;d8d8d8;ffffff

# Text colors
term_foreground: ffffff
term_foreground_bright: ffffff
term_background_bright: 191919
