text             = "#ececec"
placeholder      = "#b0b0b0"
text-error       = "#ececec"
border           = "rgba(ffffff99) rgba(ffffff26) 45deg"
border-active    = "rgba(ffffff99) rgba(ffffff26) 45deg"
border-error     = "#a8a8a8"
